#!/usr/bin/bash

MY_SHELL="oil"

if [ "$MY_SHELL" = "bash" ]
then
  echo "You seem to like the bash shell."
elif [ "$MY_SHELL" = "fish" ]
then
  echo "You seem to like the fish shell."
else
  echo "You don't seem to like the bash or fish shells."
fi
