#!/usr/bin/bash

# Modify the previous script so that it accepts the file or directory name as an
# argument instead of
# prompting the user to enter it.

FILE=$1

if [ -f "$FILE" ]
then
  echo "File exists and is a regular file."
elif [ -d "$FILE" ]
then
  echo "File exists and is a directory."
else
  echo "File does not exist."
fi

ls -l $FILE
