#!/usr/bin/bash

# Write a shell script that prompts the user for a name of a file or directory
# and reports if it is a regular file,
# a directory, or another type of file.
# Also perform an ls command against the file or directory with the long
# listing option.

read -p "Type name of file: " FILE

if [ -f "$FILE" ]
then
  echo "File exists and is a regular file."
elif [ -d "$FILE" ]
then
  echo "File exists and is a directory."
else
  echo "File does not exist."
fi

ls -l $FILE
