#!/usr/bin/bash

# Write a shell script that displays "man", "bear", "pig", "dog", "cat", and
# "sheep" on the screen with each appearing on a separate line. 
# Try to do this in as few lines as possible.
# Hint: Loops can be used to perform repetitive tasks.

LIST="man bear pig dog cat sheep"

for animal in $LIST
do
  echo $animal
done
