#!/usr/bin/bash

# Write a shell script that accepts a file or directory name as an argument.
# Have the script report if it is a regular file, a directory, or another type of file. 
# If it is a regular file, exit with a 0 exit status. 
# If it is a directory, exit with a 1 exit status. 
# If it is some other type of file, exit with a 2 exit status.

FILE=$1

if [ -f "$FILE" ]
then
  echo "$FILE exists and is a regular file."
  echo "Exit 0"
  exit 0
elif [ -d "$FILE" ]
then
  echo "$FILE is a directory."
  echo "Exit 1"
  exit 1
else
  echo "$FILE does not exist or is a file of another type."
  echo "Exit 2"
  exit 2
fi
