#!/usr/bin/bash

shopt -s nullglob

# Write a shell script that renames all files in the current directorythat end in ".jpg" to begin with today's
# date in the following format: YYYY-MM-DD. For example, if a picture of mycat was in the current
# directory and today was October 31, 2016 it would change name from "mycat.jpg" to "2016-10-31-mycat.jpg".
# Hint: Look at the format options for the date command.
# For "extra credit", make sure to gracefully handle instances where there are no ".jpg" files in the current
# directory. (Hint: man bash and read the section on the nullglob option.)

# Create a set of .jpg files: touch {1..5}.jpg OR in fish touch (seq 1 5).jpg

for FILE in *.jpg
do
  mv $FILE $(date +%F)-${FILE}
done
