#!/usr/bin/bash

shopt -s nullglob

# Write a script that renames files based on the file extension. The script should prompt the user for a
# file extension. Next, it should ask the user what prefix to prepend to the file name(s). By default, the
# prefix should be the current date in YYYY-MM-DD format. If the user simply presses enter, the current
# date will be used. Otherwise, whatever the user entered will be used as the prefix. Next, it should
# display the original file name and the new name of the file. Finally, it should rename the file.

# Handle user input
read -p "Please enter a file extension: " EXT
read -p "Please enter a prefix (press ENTER for YYYY-MM-DD): " PREFIX

# If only ENTER (empty string) then set PREFIX to date
if [ -z "$PREFIX" ] 
then 
  PREFIX=$(date +%F) 
fi

for FILE in *.$EXT
do
  echo "Renaming $FILE to $PREFIX-$FILE"
#  mv $FILE $PREFIX-$FILE
done
